accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [path("signup/", SignUpView.as_view(), name="signup")]

blog/urls.py
from django.urls import path
from .views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)

urlpatterns = [
    path("", BlogListView.as_view(), name="home"),
    path("post/<int:pk>/", BlogDetailView.as_view(), name="post_detail"),
    path("post/new/", BlogCreateView.as_view(), name="post_new"),
    path("post/<int:pk>/edit/", BlogUpdateView.as_view(), name="post_edit"),
    path("post/<int:pk>/delete/", BlogDeleteView.as_view(), name="post_delete"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("blog.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    body = models.TextField()

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"pk": self.pk})

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

# Create your views here.


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

blog/views.py
from django.shortcuts import render
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import Post
from django.urls import reverse_lazy


# Create your views here.
class BlogListView(ListView):
    model = Post
    template_name = "home.html"


class BlogDetailView(DetailView):
    model = Post
    template_name = "post_detail.html"


class BlogCreateView(CreateView):
    model = Post
    template_name = "post_new.html"
    fields = ["title", "author", "body"]


class BlogUpdateView(UpdateView):
    model = Post
    template_name = "post_edit.html"
    fields = ["title", "body"]


class BlogDeleteView(DeleteView):
    model = Post
    template_name = "post_delete.html"
    success_url = reverse_lazy("home")

templates/base.html
<html>
    {% load static %}
    <head>
        <title>
            Blog 
        </title>
        <link rel="stylesheet" href="{%  static 'css/base.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400"
rel="stylesheet">
    </head>

    
<body>
    <div>
    <header>
    <div class="nav-left">
        <h1><a href="{% url 'home' %}">Django Blog</a></h1>
    </div>
    <div class="nav-right">
        <a href="{% url 'post_new' %}">+ New Blog Post</a>
    </div>
    </header>
    {% if user.is_authenticated %}
    <p>Hi {{ user.username }}!</p>
    <form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    
    <input type="submit" value="Logout">
    </form>
    {% else %}
    <p>you are not logged in </p>
    <a href="{%  url 'login' %}"> Login</a>
    <a href="{% url 'signup' %}">Sign up</a>
    {% endif %}
        {% block content %}{% endblock content %}
    
    </div>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block content %}
<ul>
    {% for post in post_list   %}

    <div class="post-entry">
        <h2> <a href="{{ post.get_absolute_url }}">{{post.title}} </a> </h2> 
        <p>{{post.body}}</p>
        </div>
    
    {% endfor %}
</ul>
{% endblock content %}

templates/post_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Delete Post</h1>
<form action="" method='post'>
    {% csrf_token %}
    <p>Are you sure you want to delete {{post.title}}?</p>
    <input type="submit" value="Confirm?">
</form>
{% endblock content %}

templates/post_detail.html
{% extends "base.html" %}

{% block content %}
<div class="post-entry">
    <h2>{{object.title}}</h2>
    <p>{{object.body}}</p>
</div>
<div>
    <a href="{%  url 'post_edit' post.pk %}">+ Edit Blog Post</a>
    <a href="{% url 'post_delete' post.pk %}">- Delete Post </a>
</div>
{% endblock content %}

templates/post_edit.html
{% extends "base.html" %}
{% block content %}
<div>
    <h1>Edit Post</h1>
    <form action="{%  url 'post_edit' post.pk %}" method="post">
     {% csrf_token %}
     {{ form.as_p }}
     <input type="submit" value="Update">
    </form>
</div>
{% endblock content %}

templates/post_new.html
{% extends "base.html" %}
{% block content %}
    <h1>New Post</h1>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save">
        </form>
    </div>
{% endblock content %}